services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/cert:/etc/nginx/cert
      - /data/nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
    links:
      - minio
    depends_on:
      - minio

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: AnvAtBJL
    volumes:
      - /data/minio:/data

  xray:
    image: teddysun/xray
    restart: always
    volumes:
      - /data/xray/config.json:/etc/xray/config.json
      - /data/cert/default:/etc/xray/cert
    ports:
      - 443:443
    links:
      - nginx
    depends_on:
      - nginx
